name: Run Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ secrets.ENV }} # .env file content
      CI: true

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.15.x'
      - run: npm install
      - run: npm test
