name: Run Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'  # Любая версия Node.js
    - run: npm install  # Установить зависимости
    - run: npm test  # Запустить тесты
